# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: 
  aws-s3: circleci/aws-s3@3.0.0

workflows:
  acme_operations_consul:
    jobs:
      - copy_files_into_s3
      - create_infrastructure:
          requires: 
          - copy_files_into_s3

jobs:
  copy_files_into_s3:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - aws-s3/copy:
          from: configuration/consul-server-config.hcl
          to: 's3://acmeoperations-consul/ConsulConfig/consul-server-config.hcl'
      - aws-s3/copy:
          from: configuration/consul.service
          to: 's3://acmeoperations-consul/ConsulConfig/consul.service'
      - aws-s3/copy:
          from: fizzbuzz/consul_cv.sh
          to: 's3://acmeoperations-consul/fizz-buzz/consul_cv.sh'
      - aws-s3/copy:
          from: fizzbuzz/consul_cv.sh
          to: 's3://acmeoperations-consul/fizz-buzz/fizzbuzz_module.py' 
          from: fizzbuzz/*
          to: 's3://acmeoperations-consul/fizz-buzz/*' 
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Deploying Infrastructure
          command: |
            aws cloudformation deploy \
              --template-file consul_infrastructure_build.yml \
              --stack-name AcmeOps-consul\
              --capabilities CAPABILITY_NAMED_IAM
