# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

workflows:
  my_workflow:
    jobs:
      - create_infrastructure

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Deploying Infrastructure
          command: |
            aws cloudformation deploy \
              --template-file consul_infrastructure_build.yml \
              --stack-name snowplow_consul_cluster
              --region=eu-west-1
