# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: 
  aws-s3: circleci/aws-s3@3.0.0

workflows:
  acme_operations_consul:
    jobs:
      - copy_consul_config
      - create_infrastructure

jobs:
  copy_consul_config:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - aws-s3/copy:
          from: configuration/consul-server-config.hcl
          to: 's3://acmeoperations-consul/ConsulConfig/consul-server-config.hcl'
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Deploying Infrastructure
          command: |
            aws cloudformation deploy \
              --template-file consul_infrastructure_build.yml \
              --stack-name snowplow-consul-cluster
